name: Build and Deploy NuGet

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build Merchrocket.Client

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build Merchrocket.Client
      - name: Pack
        run: dotnet pack -c Release -o Packages Merchrocket.Client
      - name: Publish NuGet package
        run: dotnet nuget push "Packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY  }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY  }}
